version: '3.8'

services:
  ravendb:
    image: ravendb/ravendb:latest
    ports:
      - "8080:8080"
    volumes:
      - ravendb-data:/var/lib/ravendb/Data
    networks:
      - my-network

  custom-image:
    build: .
    ports:
      - "5555:80"
    depends_on:
      - ravendb
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  ravendb-data:
